# Generated by Django 2.2.5 on 2020-01-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='pofile_pic',
            new_name='profile_pic',
        ),
    ]
